# Generated by Django 4.2.6 on 2023-11-12 18:53

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BadgeDonneur',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
            ],
            options={
                'verbose_name': 'Badge de donneur',
                'verbose_name_plural': 'Badge de donneurs',
            },
        ),
        migrations.CreateModel(
            name='Collect',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('image', models.ImageField(upload_to='collects/')),
                ('description', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('post_at', models.DateField(blank=True, null=True)),
                ('goal', models.DecimalField(decimal_places=0, max_digits=10)),
                ('raised', models.DecimalField(decimal_places=0, default=0, max_digits=10)),
                ('end_date', models.DateTimeField(blank=True, null=True)),
                ('confirmer', models.BooleanField(default=False)),
                ('posted', models.BooleanField(default=False)),
                ('is_amount_reached', models.BooleanField(default=False)),
                ('by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Collect',
                'verbose_name_plural': 'Collects',
            },
        ),
        migrations.CreateModel(
            name='Contacts',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(auto_now_add=True)),
                ('first_name', models.CharField(max_length=50)),
                ('last_name', models.CharField(max_length=50)),
                ('email', models.EmailField(max_length=254, unique=True)),
            ],
            options={
                'verbose_name': 'Contacts',
                'verbose_name_plural': 'Contacts',
            },
        ),
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(auto_now_add=True)),
                ('first_name', models.CharField(max_length=50)),
                ('last_name', models.CharField(max_length=50)),
                ('email', models.EmailField(max_length=254)),
                ('object', models.CharField(default='Renseignement', max_length=50)),
                ('content', models.TextField()),
                ('read', models.BooleanField(default=False)),
                ('replied', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name': 'Message',
                'verbose_name_plural': 'Messages',
            },
        ),
        migrations.CreateModel(
            name='Newsletters',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(auto_now_add=True)),
                ('email', models.EmailField(max_length=254, unique=True)),
            ],
            options={
                'verbose_name': 'Newsletter',
                'verbose_name_plural': 'Newsletters',
            },
        ),
        migrations.CreateModel(
            name='PayementMethod',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('logo', models.FileField(blank=True, null=True, upload_to='logos')),
                ('usage_number', models.IntegerField(default=0)),
                ('total_amount', models.DecimalField(decimal_places=0, default=0, max_digits=10)),
            ],
            options={
                'verbose_name': 'Methode de payement',
                'verbose_name_plural': 'Methodes de payement',
            },
        ),
        migrations.CreateModel(
            name='Site',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('logo', models.FileField(upload_to='site/')),
                ('avatar', models.ImageField(upload_to='site/')),
                ('favicon', models.FileField(upload_to='Site/')),
            ],
            options={
                'verbose_name': 'site',
                'verbose_name_plural': 'sites',
            },
        ),
        migrations.CreateModel(
            name='Volunteer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(auto_now_add=True)),
                ('name', models.CharField(max_length=250)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('sujet', models.CharField(max_length=50)),
                ('cv', models.FileField(upload_to='members/volunteer/cv')),
                ('comment', models.TextField()),
                ('approuved', models.BooleanField(default=False)),
                ('approved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Volunteer',
                'verbose_name_plural': 'Volunteers',
            },
        ),
        migrations.CreateModel(
            name='EvenementCampagne',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titre', models.CharField(max_length=200)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('description', models.TextField()),
                ('date_debut', models.DateTimeField()),
                ('date_fin', models.DateTimeField()),
                ('lieu', models.CharField(max_length=200)),
                ('objectifs', models.TextField()),
                ('image', models.ImageField(upload_to='campages/')),
                ('type_evenement', models.CharField(choices=[('Don de sande', 'Don de sande'), ('campagne medical', 'campagne medical')], max_length=50)),
                ('participant', models.IntegerField(default=0)),
                ('custom_fields', models.JSONField(blank=True, null=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('oraganisateurs', models.ManyToManyField(blank=True, related_name='evenements_inscrits', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Donneur',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='anonyme', max_length=100)),
                ('email', models.CharField(max_length=250)),
                ('create_at', models.DateField(auto_now_add=True)),
                ('total_don', models.IntegerField(default=0)),
                ('badges', models.ManyToManyField(blank=True, to='administration.badgedonneur')),
            ],
            options={
                'verbose_name': 'Donneur',
                'verbose_name_plural': 'Donneurs',
            },
        ),
        migrations.CreateModel(
            name='DonCollect',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(auto_now_add=True)),
                ('donneur_name', models.CharField(blank=True, max_length=50)),
                ('donneur_email', models.EmailField(blank=True, max_length=254)),
                ('amount', models.IntegerField()),
                ('payement_method', models.CharField(blank=True, default='wave', max_length=50)),
                ('confirmed', models.BooleanField(default=True)),
                ('added_by_admin', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Ajoute par')),
                ('collect', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='administration.collect', verbose_name='Collect du don')),
            ],
            options={
                'verbose_name': 'Don de collect',
                'verbose_name_plural': 'Dons de collect',
            },
        ),
    ]
