# Generated by Django 4.2.6 on 2023-10-28 19:06

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Collect',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('image', models.ImageField(height_field=100, upload_to='collects/', width_field=100)),
                ('description', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('post_at', models.DateField(auto_now=True)),
                ('amount', models.DecimalField(decimal_places=5, max_digits=10)),
                ('collected_amount', models.DecimalField(decimal_places=5, default=0, max_digits=10)),
                ('end_date', models.DateTimeField()),
                ('is_amount_reached', models.BooleanField(default=False)),
                ('by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Collect',
                'verbose_name_plural': 'Collects',
            },
        ),
    ]
