# Generated by Django 4.2.6 on 2023-10-28 19:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('administration', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='collect',
            old_name='amount',
            new_name='goal',
        ),
        migrations.RenameField(
            model_name='collect',
            old_name='collected_amount',
            new_name='raised',
        ),
    ]
