# Generated by Django 4.2.6 on 2023-10-28 19:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administration', '0002_rename_amount_collect_goal_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='collect',
            name='post_at',
            field=models.DateField(),
        ),
    ]
