# Generated by Django 4.2.6 on 2023-10-28 19:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administration', '0003_alter_collect_post_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='collect',
            name='image',
            field=models.ImageField(upload_to='collects/'),
        ),
        migrations.AlterField(
            model_name='collect',
            name='raised',
            field=models.DecimalField(decimal_places=20, default=0, max_digits=20),
        ),
    ]
