# Generated by Django 4.2.6 on 2023-11-14 00:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('administration', '0003_alter_evenementcampagne_type_evenement'),
    ]

    operations = [
        migrations.RenameField(
            model_name='evenementcampagne',
            old_name='image',
            new_name='image_event',
        ),
    ]
