# Generated by Django 4.2.6 on 2023-11-14 01:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('administration', '0004_rename_image_evenementcampagne_image_event'),
    ]

    operations = [
        migrations.RenameField(
            model_name='evenementcampagne',
            old_name='image_event',
            new_name='image',
        ),
    ]
