# Generated by Django 4.2.6 on 2023-10-29 00:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administration', '0006_site'),
    ]

    operations = [
        migrations.AddField(
            model_name='collect',
            name='posted',
            field=models.BooleanField(default=False),
        ),
    ]
