# Generated by Django 4.2.6 on 2023-10-29 01:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administration', '0007_collect_posted'),
    ]

    operations = [
        migrations.AlterField(
            model_name='collect',
            name='goal',
            field=models.DecimalField(decimal_places=0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='collect',
            name='raised',
            field=models.DecimalField(decimal_places=0, default=0, max_digits=10),
        ),
    ]
