# Generated by Django 4.2.6 on 2023-10-29 16:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administration', '0008_alter_collect_goal_alter_collect_raised'),
    ]

    operations = [
        migrations.AddField(
            model_name='collect',
            name='confirmer',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='collect',
            name='end_date',
            field=models.DateTimeField(null=True),
        ),
    ]
