# Generated by Django 4.2.6 on 2023-10-30 14:36

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('administration', '0009_collect_confirmer_alter_collect_end_date'),
    ]

    operations = [
        migrations.CreateModel(
            name='BadgeDonneur',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
            ],
            options={
                'verbose_name': 'Badge de donneur',
                'verbose_name_plural': 'Badge de donneurs',
            },
        ),
        migrations.CreateModel(
            name='PayementMethod',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('usage_number', models.IntegerField(default=0)),
                ('total_amount', models.DecimalField(decimal_places=0, default=0, max_digits=10)),
            ],
            options={
                'verbose_name': 'Methode de payement',
                'verbose_name_plural': 'Methodes de payement',
            },
        ),
        migrations.CreateModel(
            name='Donneur',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='anonyme', max_length=100)),
                ('email', models.CharField(max_length=250)),
                ('create_at', models.DateField(auto_now_add=True)),
                ('total_don', models.IntegerField(default=0)),
                ('badges', models.ManyToManyField(blank=True, null=True, to='administration.badgedonneur')),
            ],
            options={
                'verbose_name': 'Donneur',
                'verbose_name_plural': 'Donneurs',
            },
        ),
        migrations.CreateModel(
            name='DonCollect',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(auto_now_add=True)),
                ('amount', models.IntegerField()),
                ('confirmed', models.BooleanField(default=True)),
                ('added_by_admin', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Ajoute par')),
                ('collect', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='administration.collect', verbose_name='Collect du don')),
                ('donneur', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='administration.donneur')),
                ('payement_method', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='administration.payementmethod', verbose_name='Methode de payement')),
            ],
            options={
                'verbose_name': 'DonCollect',
                'verbose_name_plural': 'DonCollects',
            },
        ),
    ]
