# Generated by Django 4.2.6 on 2023-10-30 14:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administration', '0010_badgedonneur_payementmethod_donneur_doncollect'),
    ]

    operations = [
        migrations.AlterField(
            model_name='donneur',
            name='badges',
            field=models.ManyToManyField(blank=True, to='administration.badgedonneur'),
        ),
    ]
