# Generated by Django 4.2.6 on 2023-10-31 16:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administration', '0011_alter_donneur_badges'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='doncollect',
            options={'verbose_name': 'Don de collect', 'verbose_name_plural': 'Dons de collect'},
        ),
        migrations.AddField(
            model_name='payementmethod',
            name='logo',
            field=models.FileField(blank=True, null=True, upload_to='logos'),
        ),
    ]
