# Generated by Django 4.2.6 on 2023-10-31 17:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administration', '0012_alter_doncollect_options_payementmethod_logo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='collect',
            name='post_at',
            field=models.DateField(blank=True),
        ),
    ]
