# Generated by Django 4.2.6 on 2023-10-31 17:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administration', '0014_alter_collect_end_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='collect',
            name='post_at',
            field=models.DateField(blank=True, null=True),
        ),
    ]
