# Generated by Django 4.2.6 on 2023-11-01 10:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administration', '0015_alter_collect_post_at'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='doncollect',
            name='donneur',
        ),
        migrations.AddField(
            model_name='doncollect',
            name='donneur_email',
            field=models.EmailField(blank=True, max_length=254),
        ),
        migrations.AddField(
            model_name='doncollect',
            name='donneur_name',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
