# Generated by Django 4.2.6 on 2023-11-06 13:40

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('administration', '0016_remove_doncollect_donneur_doncollect_donneur_email_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='EvenementCampagne',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titre', models.CharField(max_length=200)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('description', models.TextField()),
                ('date_debut', models.DateTimeField()),
                ('date_fin', models.DateTimeField()),
                ('lieu', models.CharField(max_length=200)),
                ('objectifs', models.TextField()),
                ('image', models.ImageField(upload_to='campages/')),
                ('type_evenement', models.CharField(choices=[('Don de sande', 'Don de sande'), ('campagne medical', 'campagne medical')], max_length=50)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
