# Generated by Django 4.2.6 on 2023-11-06 13:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administration', '0017_evenementcampagne'),
    ]

    operations = [
        migrations.AddField(
            model_name='evenementcampagne',
            name='participant',
            field=models.IntegerField(default=0),
        ),
    ]
