# Generated by Django 4.2.6 on 2023-11-06 17:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administration', '0018_evenementcampagne_participant'),
    ]

    operations = [
        migrations.AddField(
            model_name='evenementcampagne',
            name='custom_fields',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
