# Generated by Django 4.2.6 on 2023-11-06 17:33

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('administration', '0019_evenementcampagne_custom_fields'),
    ]

    operations = [
        migrations.AddField(
            model_name='evenementcampagne',
            name='oraganisateurs',
            field=models.ManyToManyField(blank=True, related_name='evenements_inscrits', to=settings.AUTH_USER_MODEL),
        ),
    ]
