# Generated by Django 4.2.6 on 2023-11-09 13:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administration', '0023_alter_contacts_options_alter_newsletters_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='object',
            field=models.CharField(default='Renseignement', max_length=50),
        ),
    ]
