# Generated by Django 4.2.6 on 2023-11-04 18:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('paiement', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notificationpaytech',
            name='client_phone',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
