# Generated by Django 4.2.6 on 2023-11-04 18:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('paiement', '0002_alter_notificationpaytech_client_phone'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notificationpaytech',
            name='currency',
            field=models.CharField(blank=True, max_length=3, null=True),
        ),
        migrations.AlterField(
            model_name='notificationpaytech',
            name='env',
            field=models.CharField(max_length=10),
        ),
        migrations.AlterField(
            model_name='notificationpaytech',
            name='payment_method',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='notificationpaytech',
            name='type_event',
            field=models.CharField(max_length=20),
        ),
    ]
