# Generated by Django 4.2.6 on 2023-11-15 20:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('task', '0003_remove_workspacecolumn_background_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='workspace',
            options={'verbose_name': 'Workspace', 'verbose_name_plural': 'Workspaces'},
        ),
        migrations.AlterModelOptions(
            name='workspacecolumn',
            options={'verbose_name': 'WorkspaceColumn', 'verbose_name_plural': 'WorkspaceColums'},
        ),
    ]
