# Generated by Django 4.2.6 on 2023-11-16 00:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('task', '0004_alter_workspace_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='columncard',
            name='date',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='columncard',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='workspace',
            name='date',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='workspacecolumn',
            name='date',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
