# Generated by Django 4.2.6 on 2023-11-16 04:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('task', '0005_alter_columncard_date_alter_columncard_description_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='columncard',
            name='image',
            field=models.ImageField(null=True, upload_to='task/workspace/card/image'),
        ),
    ]
