# Generated by Django 4.2.6 on 2023-11-16 05:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('task', '0006_columncard_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='columncard',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='task/workspace/card/image'),
        ),
    ]
